### ISSUE TITLE
Missing python script

### ISSUE THREAD

**Issue by dominik-warch** [soduco/ICDAR-2021-Vectorization#5]
In the readme 3.3.1 you describe the use of the python script `create_image_batch.py` which is not part of the repository.

```
python ./data_generator/create_image_batch.py <map_image_input> <ground_truth_image_input> <output_directory>
```

**Comment by jchazalon** [comment]
Dear @dominik-visca 
thanks for pointing this issue, which we will fix.
Unfortunately, most of us are in holidays right now, and you may have to wait for a few more days.

@chenyizi086 could you please have a look at this when you are back from holidays?
Thanks!

**Comment by chenyizi086** [comment]
Dear @dominik-visca 
I made a typo in readme where the file should be create_tilling.py instead of create_image_batch.py.
I have already fixed this issue in the repository and thank you very much for pointing this out.

Wish you a good day,
